ALTER TYPE "AuditAction" ADD VALUE 'FILE_UPLOAD';
ALTER TYPE "AuditAction" ADD VALUE 'SIGN_IN';
ALTER TYPE "AuditAction" ADD VALUE 'SIGN_OUT';
ALTER TYPE "AuditAction" ADD VALUE 'MEMBER_ADD';
ALTER TYPE "AuditAction" ADD VALUE 'MEMBER_REMOVE';
ALTER TYPE "AuditAction" ADD VALUE 'ROLE_CHANGE';
ALTER TYPE "AuditAction" ADD VALUE 'LOGIN_FAILED';
