-- Phase S: add TEAM_LEADER and OPERATIONS_MANAGER to SystemRole enum.

ALTER TYPE "public"."SystemRole" ADD VALUE IF NOT EXISTS 'TEAM_LEADER';
ALTER TYPE "public"."SystemRole" ADD VALUE IF NOT EXISTS 'OPERATIONS_MANAGER';
