'use server'

// Server Actions in this file are intentionally public — reachable by a
// department approver (e.g. Accounting, Customer Success) who has no
// account in this system. actOnClearanceApprovalPublic authenticates via the
// per-department token generated by initiateExitClearance() instead of
// requireAuth()/requireRole(); see the PUBLIC_TOKEN_ACTIONS exception in
// scripts/check-action-auth.ts.

import { prisma } from '@/lib/prisma'
import { revalidatePath, revalidateTag } from 'next/cache'
import { CACHE_TAGS } from '@/lib/cache'
import { logAudit } from '@/lib/audit'
import { getPublicFormActorId } from '@/lib/public-actor'
import type { ClearanceApprovalStatus } from '@/src/generated/prisma/enums'

export async function actOnClearanceApprovalPublic(token: string, formData: FormData) {
  const approval = await prisma.exitClearanceApproval.findUnique({
    where: { token },
    include: { termination: { select: { id: true, vaProfileId: true, ticketId: true, workflowStatus: true } } },
  })
  if (!approval) throw new Error('This approval link is invalid.')
  if (approval.termination.workflowStatus !== 'CLEARANCE_PROCESSING') {
    throw new Error('This clearance is no longer open for department action.')
  }
  if (approval.status !== 'PENDING') {
    throw new Error('This department has already acted on this clearance.')
  }

  const approverName = ((formData.get('approverName') as string) || '').trim()
  const statusRaw = (formData.get('status') as string) || ''
  const comments = ((formData.get('comments') as string) || '').trim() || null
  if (!approverName) throw new Error('Your name is required.')
  if (!['APPROVED', 'REJECTED'].includes(statusRaw)) throw new Error('Missing or invalid decision.')
  if (statusRaw === 'REJECTED' && !comments) {
    throw new Error('A comment describing the outstanding requirement is required when rejecting.')
  }

  await prisma.exitClearanceApproval.update({
    where: { id: approval.id },
    data: { status: statusRaw as ClearanceApprovalStatus, approverName, comments, actionDate: new Date() },
  })

  const allApprovals = await prisma.exitClearanceApproval.findMany({ where: { terminationId: approval.terminationId } })
  const allApproved = allApprovals.every((a) => (a.id === approval.id ? statusRaw === 'APPROVED' : a.status === 'APPROVED'))

  const actorId = await getPublicFormActorId()

  if (allApproved) {
    await prisma.termination.update({
      where: { id: approval.terminationId },
      data: { workflowStatus: 'COMPLIANCE_REVIEW_PENDING' },
    })
    await logAudit({
      actorId,
      action: 'STATUS_CHANGE',
      entityType: 'Termination',
      entityId: approval.terminationId,
      after: { workflowStatus: 'COMPLIANCE_REVIEW_PENDING' },
      metadata: { reason: 'All 5 departments approved (last via public link)' },
    })
  }

  await logAudit({
    actorId,
    action: statusRaw === 'APPROVED' ? 'APPROVE' : 'REJECT',
    entityType: 'ExitClearanceApproval',
    entityId: approval.id,
    after: { status: statusRaw, comments, approverName },
    metadata: { department: approval.department, viaForm: 'exit-clearance-public-link' },
  })

  revalidatePath(`/vas/${approval.termination.vaProfileId}`)
  if (approval.termination.ticketId) revalidatePath(`/tickets/${approval.termination.ticketId}`)
  revalidatePath('/offboarding')
  revalidatePath(`/offboarding/${approval.terminationId}`)
  revalidateTag(CACHE_TAGS.tickets, 'default')
}
